monitoring:
    logging:
        app_level: ENC[AES256_GCM,data:jVMNRaY=,iv:WBINqrRPq3MLPUluDAn2Y2JmqkvWra3kABARzV5Hk5Q=,tag:GqawklThm8vbHf4FTLHYTg==,type:str]
database:
    mode: ENC[AES256_GCM,data:AyhMldQ/4uoK,iv:BAap4ihblTftVBKQxtd1QNmV7r4JwJiSJ8bJlG0Zjlk=,tag:RoqDwy4mrdmkB5hS1DcBoA==,type:str]
    cosmos_db:
        access_key: ENC[AES256_GCM,data:6xu0TRY/ObfwSogqwcp0ntfg34z2eurQeNXKaq41Gza2/E+GR7OBG5L/WdwHBMxv2nbrgf33YRbmdVzx7daYSmUa2ENSGxij7XkezcBKl6nIwo+8ZMluXQ==,iv:AbF4Sc8lG2a6BZrdtjQlkDgCFkLMXSYiaNXuypkifGA=,tag:6uwGM0YjA0jrUAcSBKFDyA==,type:str]
        container: ENC[AES256_GCM,data:9N437VuaJsQ=,iv:1Z7p5k/FXgIBIRDG12tUVLXUNn+oCJQP9aMxL0n2hgU=,tag:WD2IiQUeUFAhaVL9Q13EXA==,type:str]
        database: ENC[AES256_GCM,data:4KbUuD7pwfy3jLMLgnA=,iv:cQc8xfTASAeNfNLpieXTmrKBgSj3rAkLGu8yHzNEaZg=,tag:Swv8IfoyGcSaZmkEUiBQgw==,type:str]
        endpoint: ENC[AES256_GCM,data:zkcv1EKNTImp4R7p7EYvHpzJrcSD8/rGqeyEhDUC9dU+aUD7wYRa,iv:uNrFACwa5GQE5EqTQoMzZg7O5snjdY3jeisQlm6n16E=,tag:XYR8YDoLoOy86nQNqIoNpw==,type:str]
cache:
    mode: ENC[AES256_GCM,data:oyUCfgw=,iv:9Y5pufGeT839O44uVCvDC0fDpth9vOMp5sGLJQsuiwM=,tag:jCgNlmjXQYQWLg3N7W0zpw==,type:str]
    redis:
        host: ENC[AES256_GCM,data:6COG78PMzuwkBFobDk2tevCEh5XhW8Luc0xT1mHpU1Rska8=,iv:JUbAApb71fHstgw65i8594u8IDSNi5ARjIRx/nJJN68=,tag:wdhmPmhRxhSaVykPVt6FMw==,type:str]
        password: ENC[AES256_GCM,data:9sn8Q/Go78E+yUICg/X3S7M2Hs8iohHubNRhsR0jEkmjFugI6MZty4GoAbk=,iv:708q28w3dcePcKIPnrKa3CC4/bHZ3TlwWxZf84QqIjg=,tag:MuMqJBGc+GVl2Us72sKc6Q==,type:str]
        port: ENC[AES256_GCM,data:KAgjiQ==,iv:/4h2QvGxNxUQtPwALXCIkPjyCXLDj42XFrymHpPuK/M=,tag:X/upmVjQyXauuhI+a39RVg==,type:int]
resources:
    public_url: ENC[AES256_GCM,data:ZcxjzILl6JMb1NP1HSHTgtHzUKNgZyM/dRX74gB0/V4ocbHro0yry4pg,iv:s8BFBCHKdI/knx1rBbgm1QshFyYZdsY1vM+ePftvVA8=,tag:zM7+d5vqkSWZZ72Onmlk9A==,type:str]
conversation:
    initiate:
        agent_phone_number: ENC[AES256_GCM,data:uFec6biyjMC6yFQa,iv:vmr8OP6XVtdPK/K3pO3LAILUQEcaXQiFfQx/RFDsIlU=,tag:SJLoDz1pmEWP7leh8L9hUg==,type:str]
        bot_company: ENC[AES256_GCM,data:NoXw3w5+IbHW/U8QKRpEFRU=,iv:0S7/xUF9pi5jLOimphWy9E1eDMz4ARB1Tu88Ztr44aQ=,tag:zNOJYk6kaVyno+KIt6vUOA==,type:str]
        bot_name: ENC[AES256_GCM,data:USUhmd71hg==,iv:0y6u6TV802L5pjpnE/YuND2ameIeZgXONP9W4/5BMbo=,tag:Czk4UVT4aGoKdu3xk4PWTQ==,type:str]
communication_services:
    access_key: ENC[AES256_GCM,data:t+/494XnQthngmw8LD89ST+tzwcOuUvDdbEVQ5lelHbdJbmoQ85NPrw/U482cMrdbabSGUnw2RFbaddbrX8o/m6QUmzOYdUbVP3Ds36HINx8v45t,iv:qGl7MBlZ8SlaXr2th5gSW4hLOURjn23xCGu345iG6ow=,tag:DV6mmyVQYQSbTFGLe/lMow==,type:str]
    call_queue_name: ENC[AES256_GCM,data:5vJRjMffgHHqRfRBwUXYMw==,iv:txNqid/AfWZMkJsHsCPCppuh7J4gL5HMqeu7QiliP4Y=,tag:HIu1vuiJ8za97F3KFlURNg==,type:str]
    endpoint: ENC[AES256_GCM,data:fSg4HayrtGpYEFA78kPx1UxlCTHQVRPGoB6owLE/bPyXcGCPQwGgoub2xS6sanSh43I=,iv:jGsNm2c1qxkKnWH5mANiD2FWmbbTLIcvvq5cgePsxYM=,tag:tEh/Nm+TlfwIRM8zGJPN4Q==,type:str]
    #ENC[AES256_GCM,data:CG1mV4MLJdUVsKlR,iv:9+7rpu06huBJNotYQZRQrcL3spAqlXIZkNVme+z92TU=,tag:ZPAndh2LATLTtUx/2pZVJA==,type:comment]
    phone_number: ENC[AES256_GCM,data:bjP6TAw2ZvX4ViEB,iv:ajO0s0M3cDC7tcpfMgx4mn0RBeRQSS6qpMzyVcgXPgo=,tag:vpXVXY0BI4gS6K+2F/kxEA==,type:str]
    post_queue_name: ENC[AES256_GCM,data:pHRnqAj994z1Tr0zF/kHzA==,iv:8MVdx8ZVdaTz3fypLyXnb6zd90Gt8fbs45VmhyzVfhs=,tag:Qn2XDKKSiRDihFCin4fqhA==,type:str]
    resource_id: ENC[AES256_GCM,data:xyW2olAu+2xMWO9tSA5niLOv/FNas/DEu2nhym3ylkJcV1WX,iv:aK4SohQlSPRCkKHTUJRF35O2PfULY0feJY9sj1iA2wk=,tag:30trfl45gRrw6RmDSMCn8g==,type:str]
    sms_queue_name: ENC[AES256_GCM,data:8aeZqbyi45NsUglGkT/Q,iv:yti6o+IKqBWjBb2E08GCU39+iYzrzWyPxK2ZqRtdl3Q=,tag:qMtAMEZsmjy4PLZ5L5TOGg==,type:str]
    trainings_queue_name: ENC[AES256_GCM,data:MaVzwCei2GOpK7bdlqXukzD8qQoS,iv:V1MvhKUMTi9VkTloFIsjTjOkU5UZ+Snw5vrfiKiG1vI=,tag:xezaEn5UCi/sWQOdM3+XDQ==,type:str]
cognitive_service:
    endpoint: ENC[AES256_GCM,data:8N4KhJifcgLkRrh2OwhQDgZSAbUdwqfhJTtefW/6bwWPW18BpPzt2Xwuy7lqlgf0QhZamfcvcJuIgMcTiBQHgZ4HJsKMwgh+,iv:UY3gqOaUVFn8KY2KVxM8vqYs5mZ/if1kqIgMWB8Ayag=,tag:aAT2kLkOYZ8aPoHwBaocDw==,type:str]
llm:
    fast:
        mode: ENC[AES256_GCM,data:Ug2sLopUtn8oPpKe,iv:mO9H9cujMUeuOgwD+16D2rd0Pku9ICwSbpr9fzUPt5U=,tag:lQ9d3YeC2jpcw41jav7S5g==,type:str]
        azure_openai:
            api_key: ENC[AES256_GCM,data:f3YYeY9+RGGES/Ws/3eCIR6Q4k8VNYCXHZ2Q1sx219o=,iv:4MBlpimeZTtOiyrk8A4kwGjLHyV1kQ7BHod2/EaIFSU=,tag:4mGUcrl+7V5tmF1guRrP2w==,type:str]
            context: ENC[AES256_GCM,data:R2cSqrQ=,iv:MCYmU6Q80eC92TgHCu0cVkLF+W+sWnhHRTb/PPTRQyM=,tag:pjXR2uUu+bUqv41Uby+j4w==,type:int]
            deployment: ENC[AES256_GCM,data:5sfBh4KPkdBjuS7xSmP8h4s=,iv:5+eW0gBVUb3cXSBivPSziROf2GiEAjd5p1e4db8sZKo=,tag:Nmw3tuUXqZbXQvU+v/OnzQ==,type:str]
            endpoint: ENC[AES256_GCM,data:3NHp8qHsUttMRS5i6AD0aC6y+exdUfOYyuU5IW+sBPQJq+9Pa/huEpkQ5agTvX5+a4fqhMZQxtmf,iv:2rfLumAX+e1i/ZSEy9d6oyXLsoNIL/+NuH9+9N0bCTo=,tag:sS7PlIIgqpc1SAZ3HdhBAg==,type:str]
            model: ENC[AES256_GCM,data:NfUsmlUMGAvn1l4N,iv:xPqM6IcEEladG931xSqPbnOV7XBR/mJ4tfTgtiadmVY=,tag:acX73a8yVErItetpO4BMnw==,type:str]
            streaming: ENC[AES256_GCM,data:VvFTew==,iv:Q12XsnuiRoIrVdsrNSkqJCn8O8tRn895F+CoCIXWSGA=,tag:P94GMkioiklasMjGPkfOzQ==,type:bool]
    slow:
        mode: ENC[AES256_GCM,data:qM8MbVz7lo8sfpb3,iv:yYY0CmmO5StWZUJugBkVD7mRvuIx28IPozhGHzATrMc=,tag:+G09yNUFlUTF6PEiJgWrRA==,type:str]
        azure_openai:
            api_key: ENC[AES256_GCM,data:XG1+I5/Fww2OVOFCh+8B01541e0Hhz3btUdkBdURnqA=,iv:kT+48JsqYlZdypklxMPag+K6CUUsaMuOoBgfA4T7Qmw=,tag:RBAufPbARGYH/rCYs23kpA==,type:str]
            context: ENC[AES256_GCM,data:YwXi1UPk,iv:7suOo4xYTHOXYyiT9ZpnoOXuUYJqRyk9HzrqghL512A=,tag:OO4xoZ7G6WAiniyPEPK5Vw==,type:int]
            deployment: ENC[AES256_GCM,data:BRzg5aeQ6R2U0L7+IXMIxx8=,iv:OpugLTfHUh+MBIAhA/dxClJqoXB7/W3+a1aP7vBNIj8=,tag:+xadUcT0PMS6dgcYgqTOWA==,type:str]
            endpoint: ENC[AES256_GCM,data:aFuCfXHHpm1xi2MlR9QbRI3BCp02L/TbeImv69bjfl4jkaFQXUgVxH1rvALd4qpw55xMBmT2Kzzv,iv:xHjXT5gGy7OkSrHThHx4Xix0N13/4a5KLUaD8gq6rMs=,tag:MCWtzcvWg0mYVkX1cgvnCw==,type:str]
            model: ENC[AES256_GCM,data:fejtCuOF,iv:QQDx/xxKrNw1EjzMi3jic256Gr46RHJ74ie2x2TE8ag=,tag:1RlGwDoAajSwSsQmXR7kFw==,type:str]
            streaming: ENC[AES256_GCM,data:kX90nA==,iv:QeEYmUHb2XfrbhI2Krmi/gpP6PPVy3KyweONwuZtj74=,tag:hdjziefh3I4gIYYGAw9KLQ==,type:bool]
ai_search:
    access_key: ENC[AES256_GCM,data:/FW+ztqs7DlnjUau2i877dPJ0H7xfm+QfaITOiN06HOrPg4de/8Cx2pqdeK7J3PDkxrnQg==,iv:p8c5N7dovVL16e6tz4j0bkUkfRoTwIBokNTZGWjZwCE=,tag:tVEAKQSCQIjOCw4193GhFg==,type:str]
    endpoint: ENC[AES256_GCM,data:6jBFAoKcaEgAeE04O16UR1E1kLyWdIGQJVImmqSZeu71oByjB6Q=,iv:njdSpKFFWYDpBDcSudMRiP9z+6zCslr9fUn5jP3RdgM=,tag:eaakHWDFAo+QVO/VStzr2w==,type:str]
    index: ENC[AES256_GCM,data:B2IONHIaHfhO,iv:Dq1qwgLJ1qxNLHBL/zMBx0BaATfxfHS+5ItCRp0KPeY=,tag:zGZR76DgV89N3yGyGc4bSg==,type:str]
ai_translation:
    access_key: ENC[AES256_GCM,data:LlSt4loAuIIlATLqO/V6ijDkVlijILzsdtWIYVd5R0w=,iv:SVlUPIaO8jIbUt5VhH810G7VcELW6h6qFi8OwOu2eAQ=,tag:Fatl3qRJTe8x+AcHsQddAg==,type:str]
    endpoint: ENC[AES256_GCM,data:73vfS+YiwDZpq2rCWb1r4EdhSGl+9XiE1oxKNEWM7qHzxM5XCApe48PtYPu5RDjQgo0SHZCwWz8LQH0aZXGVNOlxHS2P8jA=,iv:KKLXLPAwUsPYaCshVe4wj7NpEizu7UfDC4QQlWUegaE=,tag:gnMD+GQyBiSGBi3z6wDcbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age104x66len7wszfjum8rytkzvtvnaq4vlrcz703he9zj9ve98hhugsdvqg5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHRjeHl6Q2RkSmY0Zjhi
            RGZVc25BVjRRRlNIUGtYOWJISXlkY2FjdUVjCjVDT0tVbXYzL0M4cHdrODk1YWZN
            aTN5cWdXbXo4T3c4UU1vSGFtMi9aNzAKLS0tIEpIQXZmdnZiaHJPdXl1b0lKYzEx
            TzRvc3UzYis3QlpZMEgxZzdiaVFOZmsKXZie6RgGZhpvq6KNkBHeIH8ekv+xeCfJ
            7Edo5WtMQOfG6bLKXrzgO3Z7CTDL9ZQcdFk16GqQX/AXGXpYBFpKaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T16:25:38Z"
    mac: ENC[AES256_GCM,data:qjQ6FdNAjPoH7/4jrBNJBEBoHXTAYWxFOmcd65+Ne3tWkxQwArnRstbwScFc/fOqG1k3JLf+1ZW9SC7lQaGsQgut+bgVWpggz2AHtJPGnld3w5UbgUMhQnJnHGtZ2eF3CAB9j4BVkAPm8nxFf8XtbKSCd7GxN2I4IRu2HY7PXIo=,iv:wng+QkniLxRJwymvYekmocjKMEW6QaD+XZl5r4N9TeY=,tag:TcTubOcvPkguxfYh/3q9vg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
